name: "DMX Control Bridge"
slug: dmx
description: >
  A Home Assistant add-on to control DMX512-compatible lighting equipment using a USB-to-DMX interface.
version: "1.3.35"
url: "https://github.com/zaneclaes/ha-dmx"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
host_network: true
full_access: true
udev: true
privileged:
  - SYS_RAWIO
map:
  - config:rw
  - ssl
  - share:rw
  - addons_config:rw
ports:
  9090/tcp: 9090
image: "inzania/dmx"