name: "DMX Control Bridge"
slug: dmx
description: >
  A Home Assistant add-on to control DMX512-compatible lighting equipment using a USB-to-DMX interface.
version: "1.3.45"
url: "https://github.com/zaneclaes/ha-dmx"
arch:
  - amd64
  - aarch64
  - armv7
startup: services
boot: auto
host_network: false
options:
  device: /dev/ttyUSB0
  device_num: 2
  output_port: 0
  mqtt_host: core-mosquitto
  mqtt_port: 1883
  mqtt_user: ""
  mqtt_password: ""
schema:
  device: device(subsystem=tty)
  device_num: int
  output_port: int
  mqtt_host: str
  mqtt_port: int
  mqtt_user: str
  mqtt_password: password
udev: true
privileged:
  - SYS_RAWIO
map:
  - config:rw
  - ssl
  - share:rw
  - addons_config:rw
ports:
  9090/tcp: 9090
image: "inzania/dmx"