name: "DMX"
version: "1.1.0"
slug: dmx
description: >-
  "Long description"
arch:
  - amd64
url: "http://inzania.com"
ports:
  123/tcp: 123
map:
  - type: share
    read_only: False
  - type: ssl
  - type: homeassistant_config
    read_only: False
    path: /custom/config/path
image: inzania/dmx